create extension if not exists pgcrypto;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),

  code integer generated by default as identity,
  name text not null,
  surname text,
  document text,
  phone text,
  address text,
  company_id uuid not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint fk_customers_company
    foreign key (company_id)
    references public.companies (id)
    on delete cascade,

  constraint unique_code_customer
    unique (company_id, code),

  constraint unique_document_customer
     unique (company_id, document)
);

create or replace function public.update_updated_at_column()
returns trigger as
$$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_updated_at_customers on public.customers;

create trigger set_updated_at_customers
before update on public.customers
for each row
execute function public.update_updated_at_column();

alter table public.customers
enable row level security;


drop policy if exists "clientes_consultar_por_empresa" on public.customers;

create policy "clientes_consultar_por_empresa"
on public.customers
for select
to authenticated
using (
  company_id = public.get_user_company_id()
);


drop policy if exists "clientes_inserir_por_empresa" on public.customers;

create policy "clientes_inserir_por_empresa"
on public.customers
for insert
to authenticated
with check (
  company_id = public.get_user_company_id()
);


drop policy if exists "clientes_atualizar_por_empresa" on public.customers;

create policy "clientes_atualizar_por_empresa"
on public.customers
for update
to authenticated
using (
  company_id = public.get_user_company_id()
)
with check (
  company_id = public.get_user_company_id()
);


drop policy if exists "clientes_excluir_por_empresa" on public.customers;

create policy "clientes_excluir_por_empresa"
on public.customers
for delete
to authenticated
using (
  company_id = public.get_user_company_id()
);
