-- migration: create_products_table.sql

create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),

  code integer generated by default as identity,
  name text not null,
  company_id uuid not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint fk_products_company
    foreign key (company_id)
    references public.companies (id)
    on delete cascade,

  constraint unique_company_code
    unique (company_id, code)
);

create or replace function public.update_updated_at_column()
returns trigger as
$$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_updated_at_products on public.products;

create trigger set_updated_at_products
before update on public.products
for each row
execute function public.update_updated_at_column();