create extension if not exists pgcrypto;

create table if not exists public.sellers (
  id uuid primary key default gen_random_uuid(),

  code integer generated by default as identity,
  name text not null,
  active boolean not null default true,
  company_id uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint fk_sellers_company
    foreign key (company_id)
    references public.companies (id)
    on delete cascade,

  constraint unique_code_seller
    unique (company_id, code)
);

drop trigger if exists set_updated_at_sellers on public.sellers;

create trigger set_updated_at_sellers
before update on public.sellers
for each row
execute function public.update_updated_at_column();

alter table public.sellers
enable row level security;


drop policy if exists "vendedores_consultar_por_empresa" on public.sellers;

create policy "vendedores_consultar_por_empresa"
on public.sellers
for select
to authenticated
using (
  company_id = public.get_user_company_id()
);


drop policy if exists "vendedores_inserir_por_empresa" on public.sellers;

create policy "vendedores_inserir_por_empresa"
on public.sellers
for insert
to authenticated
with check (
  company_id = public.get_user_company_id()
);


drop policy if exists "vendedores_atualizar_por_empresa" on public.sellers;

create policy "vendedores_atualizar_por_empresa"
on public.sellers
for update
to authenticated
using (
  company_id = public.get_user_company_id()
)
with check (
  company_id = public.get_user_company_id()
);


drop policy if exists "vendedores_excluir_por_empresa" on public.sellers;

create policy "vendedores_excluir_por_empresa"
on public.sellers
for delete
to authenticated
using (
  company_id = public.get_user_company_id()
);
