-- migration: add budget_number (sequencial) + search_text (nome do cliente + número)

-- 1. Número sequencial do orçamento
alter table public.budgets
add column if not exists budget_number integer generated by default as identity;

-- 2. Coluna de busca
alter table public.budgets
add column if not exists search_text text;

update public.budgets b
set search_text = concat_ws(
  ' ',
  b.budget_number::text,
  trim(concat_ws(' ', c.name, c.surname))
)
from public.customers c
where c.id = b.customer_id;

-- 4. Função da trigger: search_text = budget_number + nome do cliente.
create or replace function public.update_budgets_search_text()
returns trigger
language plpgsql
as $$
declare
  v_customer_name text;
begin
  select trim(concat_ws(' ', c.name, c.surname))
  into v_customer_name
  from public.customers c
  where c.id = new.customer_id;

  new.search_text := concat_ws(
    ' ',
    new.budget_number::text,
    v_customer_name
  );

  return new;
end;
$$;

-- 5. Recria a trigger
drop trigger if exists trg_update_budgets_search_text on public.budgets;

create trigger trg_update_budgets_search_text
before insert or update of customer_id
on public.budgets
for each row
execute function public.update_budgets_search_text();
